### PR TITLE
fix(bigcommerce_product_agent): only try to delete something if exists

### PR DESCRIPTION
**Pull request by Jhalter5Stones**
only try to delete meta field if meta field exists

### CODE REVIEW

**Comment by Jhalter5Stones** [comment]
@mrogers-5s Can you review this? Does this look like the right way to make sure we are not trying to delete a meta field that doesn't exist?

https://trello.com/c/FraR1C3N/219-as-a-developer-i-should-fix-product-sync-bugs

**Comment by Jhalter5Stones** [comment]
@mrogers-5s Can you review this when you get the chance?

**Comment by Jhalter5Stones** [comment]
@jspizziri Can you final review this please and if it looks good merge and release?

https://trello.com/c/FraR1C3N/219-as-a-developer-i-should-fix-product-sync-bugs

**Comment by jspizziri** [comment]
@Jhalter5Stones one comment. This should be a `fix` not a `feat`. Please amend your commit message.

**Comment by Jhalter5Stones** [comment]
@jspizziri This should be fixed. Sorry about that. That is one thing I need to get better at is properly marking my change as what it actually is

**Pull request merged**
