### PR TITLE
feat(product_agent, modifier_mapper, product_mapper):set default variant

### PR DESCRIPTION
**Pull request by Jhalter5Stones**
set default variant to accuman product isdefault
https://trello.com/c/JZbfs5a8/98-usbat-see-the-product-search-category-listing-as-designed

### CODE REVIEW

**Comment by Jhalter5Stones** [comment]
@mrogers-5s Ready for review. Let me know what you think

https://trello.com/c/JZbfs5a8/98-usbat-see-the-product-search-category-listing-as-designed

**Comment by Jhalter5Stones** [comment]
@Ken-Michalak Do you know how we can publish this to https://rubygems.org/ so that we can use this in the huginn staging?

**Comment by Ken-Michalak** [comment]
No, you'll have to look into how that works. The Readme does say to use `npm version`, so I would try that first at least.

**Comment by Jhalter5Stones** [comment]
@Ken-Michalak @mrogers-5s New version is pushed. https://rubygems.org/gems/huginn_bigcommerce_product_agent/versions/1.2.0

**Pull request merged**
